<a href="https://colab.research.google.com/github/Sokhiba/BM25/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

Data science and AI / Mohirdev

2-practice

Masala(1): 2-o'lchamli massiv yaratish
Masala sharti : Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.

In [ ]:
import numpy as np

In [ ]:
massiv = np.arange(0,9,1).reshape(3,3)
massiv

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
massiv2 = np.arange(1,9,1).reshape(2,2,2)
massiv2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
massiv3 = np.arange(1,9,1).reshape(2,4,1)
massiv3

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [ ]:
massiv.shape

(3, 3)

Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni kesib olish
Masala : Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.


In [ ]:
arr = np.array([massiv[2,0],massiv[2,1]])
arr

array([6, 7])

Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish
Masala : 3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16 elementlarini kesib oluvchi funksiyani davom ettiring.
  
                [[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]]

In [ ]:
arr3 = np.arange(0,27,1).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr2 =arr3.reshape(9,3)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
slice_arr = arr2[4:6,0:2]
slice_arr

array([[12, 13],
       [15, 16]])

Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni kesib olish
Masala : Bizlarda,

    ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']
listdagi kishilar va ularning ma'lumotlari

  [[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]]
ko'rinishda keltirilgan. Mana shu ma'lumotlardan Javohir va Elyor ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini davom ettiring.

In [ ]:
names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
data = np.array([[5, 6, 1, 1], [9, 1, 1, 1], [7, 7, 4, 2], [1, 5, 1, 9], [9, 9, 4, 5], [7, 5, 9, 6], [5, 3, 7, 4]] )

mask = (names=='Javohir') | (names=='Elyor')
slice_name = data[mask];
slice_name

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])